"use client";

import { useState, useEffect } from "react";
import BackButton from "@/app/components/BackButton";
import Modal from "@/app/components/Modal";
import { db } from "@/lib/firebase";
import { collection, onSnapshot, query, where } from "firebase/firestore";

export default function DailyPlanner() {
  const meals = [
    { key: "breakfast", label: "Breakfast", color: "bg-orange-100 dark:bg-orange-800" },
    { key: "lunch", label: "Lunch", color: "bg-green-100 dark:bg-green-800" },
    { key: "snacks", label: "Snacks", color: "bg-yellow-100 dark:bg-yellow-800" },
    { key: "dinner", label: "Dinner", color: "bg-blue-100 dark:bg-blue-800" },
  ];

  const [selectedMeal, setSelectedMeal] = useState<string | null>(null);
  const [aiMeal, setAiMeal] = useState<string | null>(null);
  const [mealList, setMealList] = useState<any[]>([]);

  useEffect(() => {
    if (!selectedMeal) return;

    const q = query(
      collection(db, "meals"),
      where("type", "==", selectedMeal.toLowerCase())
    );

    const unsub = onSnapshot(q, (snapshot) => {
      const list = snapshot.docs.map((d) => ({
        id: d.id,
        ...d.data(),
      }));
      setMealList(list);
    });

    return () => unsub();
  }, [selectedMeal]);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 dark:text-white p-6">
      <BackButton />

      <h1 className="text-3xl font-bold text-green-700 dark:text-green-300 mb-6">
        Daily Meal Planner
      </h1>

      <div className="space-y-4">
        {meals.map((meal) => (
          <div
            key={meal.key}
            className={`${meal.color} p-4 rounded-xl shadow flex flex-col gap-2`}
          >
            <h2 className="text-xl font-semibold">{meal.label}</h2>

            <p className="text-gray-600 dark:text-gray-300 text-sm">
              Select a meal or generate AI meal
            </p>

            <div className="flex gap-3 mt-2">
              <button
                onClick={() => setSelectedMeal(meal.key)}
                className="px-4 py-2 bg-green-600 text-white rounded-lg shadow hover:bg-green-700"
              >
                Choose Meal
              </button>

              <button
                onClick={() => setAiMeal(meal.key)}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg shadow hover:bg-purple-700"
              >
                Generate AI Meal
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Choose Meal Modal */}
      <Modal open={selectedMeal !== null} onClose={() => setSelectedMeal(null)}>
        <h2 className="text-xl font-bold mb-3">Choose {selectedMeal}</h2>

        {mealList.length === 0 ? (
          <p className="text-gray-500">No meals found in Firebase.</p>
        ) : (
          <ul className="space-y-2">
            {mealList.map((meal) => (
              <li
                key={meal.id}
                className="p-2 border rounded hover:bg-green-100 dark:hover:bg-green-800 cursor-pointer"
              >
                {meal.name}
              </li>
            ))}
          </ul>
        )}
      </Modal>

      {/* AI Meal Modal */}
      <Modal open={aiMeal !== null} onClose={() => setAiMeal(null)}>
        <h2 className="text-xl font-bold mb-3">AI Meal for {aiMeal}</h2>
        <p className="text-gray-700 dark:text-gray-300">
          Coconut‑rich Kerala meal generated by AI (placeholder).
        </p>
      </Modal>
    </div>
  );
}
